#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 28 16:19:48 2017

@author: rammanouil
"""

# ==============================================================================
# OPEN PSF AND DIRTY CUBE - SKY to check results
# ==============================================================================

import os
import numpy as np
from astropy.io import fits
import pylab as pl
from deconv3d_tools import conv

def checkdim(x):
    if len(x.shape) == 4:
        x = np.squeeze(x)
        x = x.transpose((2, 1, 0))
    return x

folder = 'data256'
file_in = 'M31_3d_conv_256_10db'

folder = os.path.join(os.getcwd(), folder)
genname = os.path.join(folder, file_in)
psfname = genname+'_psf.fits'
drtname = genname+'_dirty.fits'

CubePSF = np.squeeze(checkdim(fits.getdata(psfname, ext=0))[:,:,0:1])
CubeDirty = np.squeeze(checkdim(fits.getdata(drtname, ext=0))[:,:,0:1])

skyname = genname+'_sky.fits'
sky = checkdim(fits.getdata(skyname, ext=0))
sky = sky[:,:,0:1]
sky = np.squeeze(sky)
sky2 = np.sum(sky*sky)

#pl.figure()
#pl.imshow(sky)
#pl.figure()
#pl.imshow(CubePSF)
#pl.figure()
#pl.imshow(CubeDirty)

#%% ==============================================================================
#
# ==============================================================================

from deconv2d import EasyMuffin, EasyMuffinSURE

#%% ===========================================================================
# Set parameters
# =============================================================================

nb=('db1','db2','db3','db4','db5','db6','db7','db8')
mu_s = 0.7
sigma=10
truesky=sky
psf=CubePSF
dirty=CubeDirty
Noise = CubeDirty - conv(CubePSF,sky)
var = np.sum(Noise**2)/Noise.size
nitermax = 50

args = {'mu_s':mu_s,'nb':nb,'truesky':sky,'psf':CubePSF,'dirty':CubeDirty,'var':var}

EM= EasyMuffin(**args)
EM.loop(nitermax)
SpectralSkyModel2 = EM.xt
cost2 = EM.costlist
snr2 = EM.snrlist
psnr2 = EM.psnrlist
wmse2 = EM.wmselist

EMs= EasyMuffinSURE(**args)
EMs.loop(nitermax)
SpectralSkyModel3 = EMs.xt
cost3 = EMs.costlist
snr3 = EMs.snrlist
psnr3 = EMs.psnrlist
psnrsure3 = EMs.psnrlistsure
wmse3 = EMs.wmselist
wmsesure3 = EMs.wmselistsure

pl.figure()
pl.plot(snr2,label='snr2')
pl.plot(snr3,'*',label='snr3')
pl.legend(loc='best')

pl.figure()
pl.plot(cost2,label='cost2')
pl.plot(cost3,'*',label='cost3')
pl.legend(loc='best')

pl.figure()
pl.plot(psnr2,label='psnr2')
pl.plot(psnr3,'*',label='psnr3')
pl.plot(psnrsure3,'*',label='psnrsure3')
pl.legend(loc='best')

pl.figure()
pl.plot(wmse2,label='wmse2')
pl.plot(wmse3,label='wmse3')
pl.plot(wmsesure3,'*',label='wmsesure3')
pl.legend(loc='best')

#%% ===========================================================================
# Test several values of mu_s
# =============================================================================

# define list of mu_s to test : Run MUFFIN and MUFFINSURE 
mu_min = -3
mu_max = 1
npoints = 40
mu_ = np.insert(np.logspace(mu_min,mu_max,npoints),0,0)

sure_ = []
mse_ = []
snr_ = []

for mu_s in mu_:
    args = {'mu_s':mu_s,'nb':nb,'truesky':sky,'psf':CubePSF,'dirty':CubeDirty,'var':var}
    EMs= EasyMuffinSURE(**args)
    EMs.loop(nitermax)
    sure_.append(EMs.wmselistsure[-1])
    mse_.append(EMs.wmselist[-1])
    snr_.append(EMs.snrlist[-1]) 


# Plot the variation of the wmse as a function of the regularization parameter
pl.figure()
pl.semilogx(mu_,10*np.log10(sure_),'-*',label='sure(lambda)')
pl.semilogx(mu_,10*np.log10(mse_),'-x',label='wmse(lambda)')
pl.legend(loc='best')

pl.figure()
pl.semilogx(mu_,snr_,'-o',label='snr(lambda)')
pl.legend(loc='best')

#%% ===========================================================================
# Re-run with the best mu_s
# =============================================================================

mu_s_opt = mu_[np.argmin(sure_)]
args = {'mu_s':mu_s_opt,'nb':nb,'truesky':sky,'psf':CubePSF,'dirty':CubeDirty,'var':var}
nitermax = 500

EMs= EasyMuffinSURE(**args)
EMs.loop(nitermax)
SpectralSkyModel3 = EMs.xt
cost3 = EMs.costlist
snr3 = EMs.snrlist
psnr3 = EMs.psnrlist
psnrsure3 = EMs.psnrlistsure
wmse3 = EMs.wmselist
wmsesure3 = EMs.wmselistsure

pl.figure()
pl.imshow(sky)
pl.figure()
pl.imshow(CubePSF)
pl.figure()
pl.imshow(CubeDirty)
pl.figure()
pl.imshow(EMs.x)

pl.figure()
pl.plot(snr3,'*',label='snr')
pl.legend(loc='best')

pl.figure()
pl.plot(cost3,'*',label='cost')
pl.legend(loc='best')

pl.figure()
pl.plot(psnr3,'*',label='psnr')
pl.plot(psnrsure3,'*',label='psnrsure')
pl.legend(loc='best')

pl.figure()
pl.plot(wmse3,label='wmse')
pl.plot(wmsesure3,'*',label='wmsesure')
pl.legend(loc='best')
